version: 2.1
orbs:
  maven: circleci/maven@1.4.1
  snyk: snyk/snyk@1.7.0
  
workflows:
  version: 2
  Build_Maven:
    jobs:
      - build
  jobs:
   build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout 
      - run: 
          name: Build with Maven.
          command: mvn clean install
