version: 2.1
orbs:
  maven: circleci/maven@1.4.1
  snyk: snyk/snyk@1.7.0
  
workflows:
  version: 2
  Snyk_workflow:
    jobs:
      - build_job
      
  jobs:
  build_job:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          command: mvn clean install
