version: 2.1
orbs:
  maven: circleci/maven@1.4.1
  snyk: snyk/snyk@1.7.0
  
workflows:
 Maven build
 maven Project:
   jobs:
     - build
  jobs:
   build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout 
      - run: 
          name: Build with Maven.
          command: mvn clean install
