version: 2.1
orbs:
  maven: circleci/maven@1.4.1
  snyk: snyk/snyk@1.7.0
workflows: 
  snyk With Maven: 
    jobs:
      - Build_Maven
      - Snyk_SCA:
          requires:
           - Build_Maven
      - Snyk_Code:
         requires:
          - Snyk_SCA
jobs:
  Build_Maven:
    docker:
      - image: circleci/openjdk:8-jdk
      
    environment:
      JAVA_HOME: /usr/lib/jvm/jdk1.8.0
    
    steps:
      - checkout 
      - run: mvn clean install
  Snyk_SCA:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - snyk/install
      - run:
          command: |
            wget https://archive.apache.org/dist/maven/maven-2/2.2.1/binaries/apache-maven-2.2.1-bin.tar.gz
            tar xf apache-maven-2.2.1-bin.tar.gz
            export PATH="$(pwd)/apache-maven-2.2.1/bin:$PATH"

            java -version
            mvn --version
            mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml"
            snyk test
          
  Snyk_Code:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - snyk/install
      - run:
          command: snyk code test
             
