version: 2.1
orbs:
  maven: circleci/maven@1.4.1
  snyk: snyk/snyk@1.7.0
workflows: 
  snyk With Maven: 
    jobs:
      - Build_Maven
      - Snyk_SCA:
          requires:
           - Build_Maven
      - Snyk_Code:
         requires:
          - Snyk_SCA
jobs:
  Build_Maven:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout 
      - run: mvn clean install
  Snyk_SCA:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - snyk/install
      - run:
          command: |
            sudo update-alternatives --set java /usr/lib/jvm/jdk1.8.0/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/jdk1.8.0/bin/javac
            export PATH="/opt/apache-maven-3.8.4/bin:$PATH"
            
            java -version
            mvn --version
            
            snyk test
          
  Snyk_Code:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - snyk/install
      - run:
          command: snyk code test
             
