version: 2.1
orbs:
  maven: circleci/maven@1.4.1
  snyk: snyk/snyk@1.7.0
workflows: 
  snyk With Maven: 
    jobs:
      - Build_Maven
      - Snyk_SCA
      - Snyk_Code
jobs:
  Build_Maven:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout 
      - run: mvn clean install
  Snyk_SCA:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - snyk/install
      - run:
          command: snyk test || exit 0
          
  Snyk_Code:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - snyk/install
      - run:
          command: snyk code test || exit 0
             
