version: 2.1
orbs:
  maven: circleci/maven@1.4.1
  snyk: snyk/snyk@1.7.0
workflows: 
  snyk With Maven: 
    jobs:
      - Build_Maven
      - Snyk_Code_Install
jobs:
  Build_Maven:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout 
      - run: mvn clean install
      
  Snyk_Code_Install:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - snyk/install
      - run:
          command: snyk code test    
