version: 2.1
orbs:
  maven: circleci/maven@1.4.1
  snyk: snyk/snyk@1.7.0
workflows: 
  build_test: 
    jobs:
      - maven_build
jobs:
  maven_build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout 
      - run: mvn clean package
