name: Commit-based Code Scanner

on:
  pull_request:
    branches:
      - '*'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set current path
        id: current-path
        run: |
          echo "::set-output name=path::$(pwd)"

      - name: Log current path and commit ID
        run: |
          echo "Current Path: ${{ steps.current-path.outputs.path }}"
          echo "Commit ID: ${{ github.sha }}"

      - name: List files and folders
        run: |
          echo "Listing folders in ${{ steps.current-path.outputs.path }}:"
          find ${{ steps.current-path.outputs.path }} -type d

      - name: List files from commit
        run: |
          echo "Listing files from commit ${{ github.event.pull_request.head.sha }}:"
          git checkout -f ${{ github.event.pull_request.head.sha }}
          git ls-files

      - name: Fix permissions
        run: |
          sudo chown -R $USER:$(id -gn) ${{ steps.current-path.outputs.path }}

      - name: Running Code scanner
        run: |
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          docker run \
            -v ${{ steps.current-path.outputs.path }}:/tmp/app \
            rohitcoder/hela --code-path /tmp/app \
            --sast --sca --secret  \
            --verbose \
            --commit-id $COMMIT_ID
