name: PR Based code Scanner

on:
  pull_request:
    branches:
      - '*'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest PR Commit ID
        id: latest-commit-id
        run: echo "::set-output name=commit-id::${{ github.event.pull_request.head.sha }}"

      - name: Create a folder for latest code
        run: mkdir -p latest_code

      - name: Copy modified files to latest code folder
        run: |
          COMMIT_ID=${{ steps.latest-commit-id.outputs.commit-id }}
          git diff-tree --no-commit-id --name-only -r $COMMIT_ID | xargs -I {} cp {} latest_code/

      - name: Log current path and commit ID
        run: |
          echo "Commit ID: ${{ steps.latest-commit-id.outputs.commit-id }}"

      - name: List files in the latest code folder
        run: |
          echo "Listing files in latest code folder:"
          ls -R latest_code/

      - name: Running Code scanner
        run: |
          COMMIT_ID=${{ steps.latest-commit-id.outputs.commit-id }}
          docker run \
            -v "$(pwd)/latest_code:/tmp/app" \
            rohitcoder/hela --code-path /tmp/app \
            --sast --sca --secret  \
            --verbose \
            --commit-id $COMMIT_ID
