name: Run Docker Command on PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Run Docker Command
      run: |
        docker run --rm rohitcoder/hela \
          --commit-id dcace5e51c11483d652891fb3146122ba41b891c \
          --code-path https://github.com/rohitcodergroww/dvja \
          --secret --sast --sca --verbose
      env:
        DOCKER_CLI_ACI: "1"  # Enable the Docker CLI with ACI (Azure Container Instances)
