name: Commit-based Code Scanner

on:
  pull_request:
    branches:
      - '*'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get path at commit
        id: commit-path
        run: |
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          COMMIT_PATH=$(git rev-parse --show-toplevel)
          echo "::set-output name=path::$COMMIT_PATH"

      - name: Log current path and commit ID
        run: |
          echo "Current Path: ${{ steps.commit-path.outputs.path }}"
          echo "Commit ID: ${{ github.event.pull_request.head.sha }}"

      - name: List folders in the commit path
        run: |
          echo "Listing folders in ${{ steps.commit-path.outputs.path }}:"
          find ${{ steps.commit-path.outputs.path }} -type d

      - name: Running Code scanner
        run: |
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          docker run \
            -v ${{ steps.commit-path.outputs.path }}:/tmp/app \
            rohitcoder/hela --code-path /tmp/app \
            --sast --sca --secret  \
            --verbose
